#!/bin/bash -ex

ldbadd -H users.ldb >/dev/null <<-EOF
dn: CN=12345,CN=Users,DC=example,DC=com
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: user
cn: 12345
uidNumber: 12345
sAMAccountName: alice
EOF

ldbadd -H users.ldb >/dev/null <<-EOF
dn: CN=54321,CN=Users,DC=example,DC=com
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: user
cn: 54321
uidNumber: 54321
sAMAccountName: bob
EOF

ldbsearch -H users.ldb | grep -q '^cn: 12345$'
ldbsearch -H users.ldb | grep -q '^sAMAccountName: alice$'

mkdir -p home link trash

test -d home -a -d link -a -d trash

# EOF
