#!/bin/bash -ex

# Create the home directory with the link.
env __NAME__='12345' hasHome='true' sAMAccountName='alice' \
	samba-ext-idm-adapter -D home -L link -T trash

test -d home/12345
test -h link/alice

touch home/12345/hello.txt
test -f link/alice/hello.txt

# EOF
