#!/bin/bash -ex

function adapter()
{
	samba-ext-idm-adapter \
		-D home -L link -T trash \
		-H users.ldb \
		-b 'CN=Users,DC=example,DC=com' \
		"${@}"
}

# Create one home directory.
__NAME__='12345' sAMAccountName='alice' adapter -u

# List all users using LDB.
adapter -l | grep -q '__UID__=12345'
adapter -l | grep -q 'sAMAccountName=alice'
adapter -l | grep -q '__UID__=54321'

# No homedir means no user.name xattr.
! ( adapter -l | grep -q 'sAMAccountName=bob' )

# List just one user by their CN.
    __UID__=12345 adapter -l | grep -q 12345
    __UID__=12345 adapter -l | grep -q alice
! ( __UID__=12345 adapter -l | grep -q 54321 )
! ( __UID__=12345 adapter -l | grep -q bob   )

    __UID__=54321 adapter -l | grep -q 54321
! ( __UID__=54321 adapter -l | grep -q bob   )
! ( __UID__=54321 adapter -l | grep -q 12345 )
! ( __UID__=54321 adapter -l | grep -q alice )

__UID__='12345' adapter -d
__UID__='54321' adapter -d

test ! -d home/12345
test ! -d home/54321

test ! -h link/alice
test ! -h link/bob


# EOF
