#!/bin/bash -ex

function adapter()
{
	samba-ext-idm-adapter \
		-D home -L link -T trash \
		-H users.ldb \
		-b 'CN=Users,DC=example,DC=com' \
		"${@}"
}

# Create one home directory and set the password hash.
__NAME__='12345' hasHome='true' sAMAccountName='alice' \
	unicodePwd='0123456789abcdef0123456789abcdef' adapter -u

# Check that the hash has been set.
__UID__='12345' adapter -l | grep -q '0123456789abcdef0123456789abcdef'

# Try two consecutive updates.
__NAME__='54321' hasHome='false' sAMAccountName='bob' \
	unicodePwd='42000000000000000000000000000000' adapter -u

__NAME__='54321' hasHome='false' sAMAccountName='bob' \
	unicodePwd='00000000000000000000000000000042' adapter -u

# Check that the hash has been set.
__UID__='54321' adapter -l | grep -q '00000000000000000000000000000042'

# Ditch the home directory, keeping the password.
__UID__='12345' hasHome='false' adapter -u

test ! -d home/12345
test ! -h link/alice


# EOF
